### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [15]:
import numpy as np

In [37]:
N = 10

In [38]:
np.arange(N-1, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [99]:
N = 10

In [253]:
matrix = np.diag(np.arange(N, -1, -1))
matrix

array([[10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [254]:
matrix.sum()

55

### Задание 3
Решите систему уравнений:
4x + 2y + z = 4,
x + 3y = 12,
5y + 4z = -3

In [118]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
a

array([[4, 2, 1],
       [1, 3, 0],
       [0, 5, 4]])

In [119]:
b = np.array([4, 12, -3])
b

array([ 4, 12, -3])

In [114]:
from numpy import linalg

In [116]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [120]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

## Задача 4 домашнего задания

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.

Матрица в виде numpy array

In [250]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [134]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [261]:
def find_similar_user(next_user):
    
    next_user_lenght = np.linalg.norm( next_user ) # сразу считаем длину вектора нового пользователя
    users_cos_dict = {} # накидаем словарь {номер строки старого пользователя (из матрицы): косинус старого с новым}
    
    for i, olden_user in enumerate(users_stats): # перебираем пользователей, enumerate для номера строки в словарь
        
        olden_user_lenght = np.linalg.norm( olden_user ) # считаем длину вектора старого пользователя с сайта
        cos = np.dot(next_user, olden_user) / (next_user_lenght * olden_user_lenght) # находим косинус с новым
        
        users_cos_dict.setdefault(i, cos) # добавляем в словарь пару {номер строки старого пользователя (из матрицы): косинус старого с новым}
    
    # находим максимальное значение в словаре    
    max_elem = None
    
    for key, value in users_cos_dict.items():
        if not max_elem or value > max_elem[1]:
            max_elem = (key, value)   
    
    print(f'Самый похожий пользователь:\nRow in user_stats - {max_elem[0]}\nStats - {users_stats[max_elem[0]]}\nCos - {max_elem[1]}')
    

In [262]:
find_similar_user(next_user_stats)

Самый похожий пользователь:
Row in user_stats - 7
Stats - [0 1 1 0 0 0]
Cos - 0.9486832980505138
